//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.14 at 08:40:09 PM IST 
//


package com.aeconnect.airshopping.aeconnect;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aeconnect.airshopping.aeconnect package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aeconnect.airshopping.aeconnect
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Augpoint }
     * 
     */
    public Augpoint createAugpoint() {
        return new Augpoint();
    }

    /**
     * Create an instance of {@link Loc }
     * 
     */
    public Loc createLoc() {
        return new Loc();
    }

    /**
     * Create an instance of {@link AirShoppingRQ }
     * 
     */
    public AirShoppingRQ createAirShoppingRQ() {
        return new AirShoppingRQ();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link POS }
     * 
     */
    public POS createPOS() {
        return new POS();
    }

}
