//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.14 at 08:40:09 PM IST 
//


package com.aeconnect.airshopping.aeconnect;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POS complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="POS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="location" type="{http://aeconnect.com/airshopping/aeconnect/}loc"/>
 *         &lt;element name="augmentationPoint" type="{http://aeconnect.com/airshopping/aeconnect/}augpoint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POS", propOrder = {
    "location",
    "augmentationPoint"
})
public class POS {

    @XmlElement(required = true)
    protected Loc location;
    @XmlElement(required = true)
    protected Augpoint augmentationPoint;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Loc }
     *     
     */
    public Loc getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Loc }
     *     
     */
    public void setLocation(Loc value) {
        this.location = value;
    }

    /**
     * Gets the value of the augmentationPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Augpoint }
     *     
     */
    public Augpoint getAugmentationPoint() {
        return augmentationPoint;
    }

    /**
     * Sets the value of the augmentationPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Augpoint }
     *     
     */
    public void setAugmentationPoint(Augpoint value) {
        this.augmentationPoint = value;
    }

}
